apiVersion: v1
kind: Secret
metadata:
  name: private-ws-stack-dados-k8s
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://jleandro10@github.com/ws-stack-dados-k8s.git
  password: ${PASSWORD}
  username: not-used